### ISSUE TITLE
Unable to open... Error when trying to view the map

### ISSUE THREAD

**Issue by saschahi** [whalehub/noita-map-viewer#3] opened 2022-03-18 15:33 UTC
I'm pretty sure i setup everything correctly. even chmodded everything to 777

getting the error:

"Unable to open [object Object]: HTTP 404 atrtempting to load TileSource"

the buttons at the bottom all load correctly (but without picture) aswell as the box in the bottom right.

I've doublechecked that every file is where it should, tried reuploading. didn't work.

Running on Ubuntu 18.04 with apache2

I've also already looked through the opensea issues and the only thing i could find is "the index.html isn't setup correctly" which makes no sense since i changed nothing

can give you link if you DM me here or on Discord saschahi#7940

**Comment by saschahi** [comment] 2022-03-18 16:24
![grafik](https://user-images.githubusercontent.com/39934087/159042714-6ee6ffd2-0323-43f1-9b11-e2a952e18a9c.png)

I've gotten a little bit further (no idea what changed it) but now it looks like this...

**Comment by whalehub** [comment] 2022-03-18 18:29
The cause of this issue was a non-existent URL in the `id` property of the IIIF3 folder's `info.json` file. The missing icons are due to the icon paths using non-relative URLs in `scripts.js`. The latter issue will be fixed in a commit shortly.

**Closed by whalehub** 2022-03-18 18:29 UTC
